name: Pika
options:
  bundleIdPrefix: com.justinmoon
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

settings:
  base:
    # Note: device builds still need a valid DEVELOPMENT_TEAM; we keep that out of git and
    # pass it via env from tools/run-ios.
    PRODUCT_BUNDLE_IDENTIFIER: com.justinmoon.pika
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.0
  configs:
    Debug:
      PRODUCT_BUNDLE_IDENTIFIER: com.justinmoon.pika.dev

targets:
  Pika:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Bindings
        excludes:
          - "*.h"
          - "*.modulemap"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - framework: Frameworks/PikaCore.xcframework
        embed: false

  PikaTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - path: Tests
    dependencies:
      - target: Pika

  PikaUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    sources:
      - path: UITests
    postCompileScripts:
      - name: "Copy .env into test bundle"
        script: |
          ENV_SRC="${SRCROOT}/../.env"
          # Copy into the xctest bundle so Bundle(for:) can find it
          XCTEST="${BUILT_PRODUCTS_DIR}/${FULL_PRODUCT_NAME}"
          if [ -d "$XCTEST" ] && [ -f "$ENV_SRC" ]; then
            cp "$ENV_SRC" "$XCTEST/env.test"
            echo "Copied .env to $XCTEST/env.test"
          elif [ -f "$ENV_SRC" ]; then
            # Fallback: put it in BUILT_PRODUCTS_DIR
            cp "$ENV_SRC" "${BUILT_PRODUCTS_DIR}/env.test"
            echo "Copied .env to ${BUILT_PRODUCTS_DIR}/env.test (fallback)"
          else
            echo "warning: .env not found at $ENV_SRC"
          fi
        basedOnDependencyAnalysis: false
    dependencies:
      - target: Pika

schemes:
  Pika:
    build:
      targets:
        Pika: all
    test:
      targets:
        - name: PikaTests
          randomExecutionOrder: true
        - name: PikaUITests
          randomExecutionOrder: true
