#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export RELEASE_VERSION_DISPLAY_NAME="./scripts/set-release-version"
exec "$SCRIPT_DIR/release-version" set-release-version "$@"
